language:
- python
sudo:
- false

python:
- 3.5
- 3.6

before_install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

script:
- flake8 lyricsbot
- pycodestyle lyricsbot
- pylint lyricsbot
- python -m unittest discover
